name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-flask-app:latest .

      - name: Run Docker container for testing
        run: |
          docker run -d --name test-container -p 5000:5000 my-flask-app:latest

      - name: Wait for application to start
        run: |
          sleep 5

      - name: Test application
        run: |
          curl -f http://localhost:5000 || exit 1

      - name: Clean up test container
        run: |
          docker stop test-container
          docker rm test-container

  push-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/nuneung1612/my-flask-app:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/nuneung1612/my-flask-app:latest
